// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 da1sh1n
// This file is part of Romzeta, licensed under the GNU General Public License
// v3.0 or later. Romzeta comes with ABSOLUTELY NO WARRANTY. See the LICENSE file
// or <https://www.gnu.org/licenses/> for details.

//! Reading `keys/*.pub` and generating the `ANCHORS` constant both build
//! scripts compile in. Shared so the listener, the installer and `xtask` read
//! the exact same files the exact same way.

#![allow(non_snake_case)] // camelCase functions

// ########## KEY FILES ##########

/// The public keys a build trusts, paired with the `.pub` file each comes
/// from. The name doubles as the file's stem — `xtask sign`'s error messages
/// build `keys/{name}.pub` from it — so this is the one place the pairing is
/// declared.
pub const ANCHOR_FILES: &[(&str, &str)] = &[("romzeta", "romzeta.pub"), ("dev", "dev.pub")];

/// Pulls the key out of a minisign `.pub` file's text, or `None` if it holds no
/// key line.
///
/// The format is a comment line then the key, but the comment is free text a
/// human may have edited, so this takes the last line that is neither blank nor
/// a comment rather than trusting the line count.
pub fn keyLine(text: &str) -> Option<&str> {
    text.lines()
        .map(str::trim)
        .rfind(|line| !line.is_empty() && !line.starts_with("untrusted comment:"))
}

/// The `ANCHORS` constant both build scripts write into `OUT_DIR`, over
/// `anchors` in the order they should be tried.
pub fn anchorsSource(anchors: &[(String, String)]) -> String {
    let mut rust = String::from(
        "// Generated by build.rs. The public keys this binary trusts, in the\n\
         // order it tries them. Not configurable at runtime, by design.\n\
         pub const ANCHORS: &[Anchor] = &[\n",
    );
    for (name, key) in anchors {
        rust.push_str(&format!(
            "    Anchor {{ name: {name:?}, base64: {key:?} }},\n"
        ));
    }
    rust.push_str("];\n");
    rust
}
